# Generated by Django 4.2.11 on 2026-04-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('hr', 'HR Manager')], default='applicant', max_length=10)),
                ('level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of known skills, e.g. ["Python", "Django", "Git"]')),
                ('portfolio_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
