# Generated by Django 4.2.11 on 2026-05-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_resume_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verified_skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills verified by passing tests'),
        ),
    ]
