# Generated by Django 4.2.11 on 2026-05-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('confirmed', 'Подтверждено'), ('completed', 'Проведено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', help_text='Ссылка на звонок или адрес', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
