# Generated by Django 4.2.11 on 2026-04-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary_min', models.IntegerField(blank=True, help_text='Min salary in KZT', null=True)),
                ('salary_max', models.IntegerField(blank=True, help_text='Max salary in KZT', null=True)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=10)),
                ('requirements_text', models.TextField(help_text='Free text requirements from HR')),
                ('training_provided', models.BooleanField(default=False)),
                ('experience_years', models.IntegerField(default=0, help_text='Required years of experience')),
                ('is_remote', models.BooleanField(default=False)),
                ('tech_stack', models.JSONField(default=list, help_text='List of technologies, e.g. ["Python", "Django"]')),
                ('detected_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='', max_length=10)),
                ('is_overqualified', models.BooleanField(default=False)),
                ('honesty_score', models.IntegerField(default=100, help_text='0-100, how honest are the requirements')),
                ('parsed_skills', models.JSONField(blank=True, default=list, help_text='Skills extracted by analyzer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='tags', to='jobs.job')),
            ],
        ),
    ]
