# Generated by Django 4.2.11 on 2026-05-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'All Tests Passed'), ('failed', 'Some Tests Failed'), ('error', 'Execution Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tests_system.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
